spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fly-foods-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
